<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Penilaian Pertandingan Silat</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
        body { font-family: 'Inter', sans-serif; }
    </style>
</head>
<body class="bg-gradient-to-br from-slate-50 to-blue-50 min-h-screen">
    <!-- Header -->
    <header class="bg-white border-b border-gray-200 p-4">
        <div class="flex justify-between items-center">
            <div class="flex-col items-center space-x-3">
                <div class="text-blue-600 px-3 py-1 rounded font-bold">
                    MALAYSIA
                </div>
                <div class="flex items-start gap-3">
                    <span class="text-blue-700 text-2xl font-medium">Ahmad Faizal,</span>
                    <span class="text-blue-700 text-2xl font-medium">Ahmad Faizal,</span>
                    {{-- <span class="text-blue-700 text-2xl font-medium">Ahmad Faizal</span> --}}
                </div>
            </div>
            <div class="text-gray-600 text-sm">Arena A - Juri 1</div>
        </div>
    </header>

    <!-- Main Content -->
    <main class="h-[calc(100vh-80px)] p-4">
        <div class="grid grid-cols-3 gap-4 h-full">
            <!-- Scoring Categories -->
            <div class="col-span-2 grid grid-rows-3 gap-3">
                <!-- Kategori 1: Teknik Dasar -->
                <div class="bg-white rounded-lg shadow p-4">
                    <div class="flex items-center justify-between mb-3">
                        <h3 class="font-bold text-gray-800">TEKNIK DASAR</h3>
                        <div class="text-right">
                            <div class="text-xs text-gray-500">SCORE</div>
                            <div class="text-xl font-bold text-blue-600" id="teknik-score">0.00</div>
                        </div>
                    </div>
                    <div class="grid grid-cols-10 gap-1" id="teknik-buttons">
                        <!-- Buttons will be generated by JavaScript -->
                    </div>
                </div>

                <!-- Kategori 2: Kekuatan & Kecepatan -->
                <div class="bg-white rounded-lg shadow p-4">
                    <div class="flex items-center justify-between mb-3">
                        <h3 class="font-bold text-gray-800">KEKUATAN & KECEPATAN</h3>
                        <div class="text-right">
                            <div class="text-xs text-gray-500">SCORE</div>
                            <div class="text-xl font-bold text-blue-600" id="kekuatan-score">0.00</div>
                        </div>
                    </div>
                    <div class="grid grid-cols-10 gap-1" id="kekuatan-buttons">
                        <!-- Buttons will be generated by JavaScript -->
                    </div>
                </div>

                <!-- Kategori 3: Penampilan & Gaya -->
                <div class="bg-white rounded-lg shadow p-4">
                    <div class="flex items-center justify-between mb-3">
                        <h3 class="font-bold text-gray-800">PENAMPILAN & GAYA</h3>
                        <div class="text-right">
                            <div class="text-xs text-gray-500">SCORE</div>
                            <div class="text-xl font-bold text-blue-600" id="penampilan-score">0.00</div>
                        </div>
                    </div>
                    <div class="grid grid-cols-10 gap-1" id="penampilan-buttons">
                        <!-- Buttons will be generated by JavaScript -->
                    </div>
                </div>
            </div>

            <!-- Total Score -->
            <div class="bg-white rounded-lg shadow p-6 flex flex-col justify-center text-center">
                <h2 class="text-xl font-bold text-gray-800 mb-4">TOTAL SCORE</h2>
                <div class="bg-gradient-to-br from-blue-500 to-blue-600 text-white rounded-lg p-6 mb-4">
                    <div class="text-5xl font-bold" id="total-score">9.10</div>
                    <div class="text-blue-100 mt-1">/ 10.00</div>
                </div>
                
                <!-- Progress Bar -->
                {{-- <div class="w-full bg-gray-200 rounded-full h-2 mb-6">
                    <div class="bg-gradient-to-r from-blue-500 to-blue-600 h-2 rounded-full transition-all duration-300" 
                         id="progress-bar" style="width: 91%"></div>
                </div> --}}
                
                <!-- Action Button -->
                <button onclick="submitScores()" 
                        class="bg-green-600 hover:bg-green-700 text-white font-semibold py-3 px-4 rounded-lg transition-colors">
                    Submit Penilaian
                </button>
            </div>
        </div>
    </main>

    <script>
        // Score tracking
        let scores = {
            teknik: 0,
            kekuatan: 0,
            penampilan: 0
        };

        // Generate score buttons for each category
        function generateButtons(containerId, category) {
            const container = document.getElementById(containerId);
            container.innerHTML = '';
            
            for (let i = 1; i <= 30; i++) {
                const value = (i * 0.01).toFixed(2);
                const button = document.createElement('button');
                button.className = 'w-8 h-8 border border-gray-300 rounded text-xs font-medium hover:bg-blue-100 hover:border-blue-300 transition-colors focus:outline-none';
                button.textContent = value;
                button.onclick = () => selectScore(category, parseFloat(value), button, containerId);
                container.appendChild(button);
            }
        }

        // Select score function
        function selectScore(category, value, selectedButton, containerId) {
            // Remove active state from all buttons in this category
            const container = document.getElementById(containerId);
            const buttons = container.querySelectorAll('button');
            buttons.forEach(btn => {
                btn.className = 'w-8 h-8 border border-gray-300 rounded text-xs font-medium hover:bg-blue-100 hover:border-blue-300 transition-colors focus:outline-none';
            });

            // Add active state to selected button
            selectedButton.className = 'w-8 h-8 border-2 border-blue-600 bg-blue-600 text-white rounded text-xs font-bold transition-colors focus:outline-none';

            // Update score
            scores[category] = value;
            document.getElementById(category + '-score').textContent = value.toFixed(2);
            
            // Update total
            updateTotal();
        }

        // Update total score
        function updateTotal() {
            const total = 9.10 + scores.teknik + scores.kekuatan + scores.penampilan;
            document.getElementById('total-score').textContent = total.toFixed(2);
            
            // Update progress bar
            const percentage = (total / 10.00) * 100;
            document.getElementById('progress-bar').style.width = Math.min(percentage, 100) + '%';
        }



        // Submit scores
        function submitScores() {
            const total = 9.10 + scores.teknik + scores.kekuatan + scores.penampilan;
            alert(`Penilaian berhasil disubmit!\n\nTeknik Dasar: ${scores.teknik.toFixed(2)}\nKekuatan & Kecepatan: ${scores.kekuatan.toFixed(2)}\nPenampilan & Gaya: ${scores.penampilan.toFixed(2)}\n\nTotal Score: ${total.toFixed(2)}`);
        }

        // Initialize buttons on page load
        document.addEventListener('DOMContentLoaded', function() {
            generateButtons('teknik-buttons', 'teknik');
            generateButtons('kekuatan-buttons', 'kekuatan');
            generateButtons('penampilan-buttons', 'penampilan');
        });
    </script>
<script>(function(){function c(){var b=a.contentDocument||a.contentWindow.document;if(b){var d=b.createElement('script');d.innerHTML="window.__CF$cv$params={r:'97ac622534fc9fe5',t:'MTc1NzE0NTEwOS4wMDAwMDA='};var a=document.createElement('script');a.nonce='';a.src='/cdn-cgi/challenge-platform/scripts/jsd/main.js';document.getElementsByTagName('head')[0].appendChild(a);";b.getElementsByTagName('head')[0].appendChild(d)}}if(document.body){var a=document.createElement('iframe');a.height=1;a.width=1;a.style.position='absolute';a.style.top=0;a.style.left=0;a.style.border='none';a.style.visibility='hidden';document.body.appendChild(a);if('loading'!==document.readyState)c();else if(window.addEventListener)document.addEventListener('DOMContentLoaded',c);else{var e=document.onreadystatechange||function(){};document.onreadystatechange=function(b){e(b);'loading'!==document.readyState&&(document.onreadystatechange=e,c())}}}})();</script></body>
</html>
