<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Penilaian Pertandingan Silat</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
    <!-- META TAG UNTUK CSRF TOKEN -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <style>
        body { font-family: 'Inter', sans-serif; }
    </style>
</head>
<body class="bg-gradient-to-br from-slate-50 to-blue-50 min-h-screen">

    @php $unit_id = $_GET['unit'] ?? '0'  @endphp
    {{-- {{ $unit_id }} --}}
    
    <!-- INPUT TERSEMBUNYI UNTUK DATA PENTING -->
    <input type="hidden" id="pertandingan_id" value="{{ $pertandingan->id ?? '0' }}">
    <input type="hidden" id="juri_id" value="{{ $user->id ?? '0' }}">
    <input type="hidden" id="role_juri" value="{{ $user->role->name ?? '0' }}">

    @if ($unit_id == 'unit_1')
        
    <input type="hidden" name="unit_id" id="unit_id" value="{{ $pertandingan->unit1_id ?? '0' }}">

    @else
    <input type="hidden" name="unit_id" id="unit_id" value="{{ $pertandingan->unit2_id ?? '0' }}">    

    @endif


    <!-- Header -->
    <header class="bg-white border-b border-gray-200 p-4">
        {{-- ... (Konten header Anda) ... --}}
    </header>

    <!-- Main Content -->
    <main class="h-[calc(100vh-80px)] p-4">
        <div class="grid grid-cols-3 gap-4 h-full">
            <!-- Scoring Categories -->
            <div class="col-span-2 grid grid-rows-3 gap-3">
                <!-- Kategori 1: Teknik Dasar -->
                <div class="bg-white rounded-lg shadow p-4">
                    <div class="flex items-center justify-between mb-3">
                        <h3 class="font-bold text-gray-800">TEKNIK DASAR</h3>
                        <div class="text-right">
                            <div class="text-xs text-gray-500">SCORE</div>
                            <div class="text-xl font-bold text-blue-600" id="teknik-score">0.00</div>
                        </div>
                    </div>
                    <div class="grid grid-cols-10 gap-1" id="teknik-buttons">
                        <!-- Buttons will be generated by JavaScript -->
                    </div>
                </div>

                <!-- Kategori 2: Kekuatan & Kecepatan -->
                <div class="bg-white rounded-lg shadow p-4">
                    <div class="flex items-center justify-between mb-3">
                        <h3 class="font-bold text-gray-800">KEKUATAN & KECEPATAN</h3>
                        <div class="text-right">
                            <div class="text-xs text-gray-500">SCORE</div>
                            <div class="text-xl font-bold text-blue-600" id="kekuatan-score">0.00</div>
                        </div>
                    </div>
                    <div class="grid grid-cols-10 gap-1" id="kekuatan-buttons">
                        <!-- Buttons will be generated by JavaScript -->
                    </div>
                </div>

                <!-- Kategori 3: Penampilan & Gaya -->
                <div class="bg-white rounded-lg shadow p-4">
                    <div class="flex items-center justify-between mb-3">
                        <h3 class="font-bold text-gray-800">PENAMPILAN & GAYA</h3>
                        <div class="text-right">
                            <div class="text-xs text-gray-500">SCORE</div>
                            <div class="text-xl font-bold text-blue-600" id="penampilan-score">0.00</div>
                        </div>
                    </div>
                    <div class="grid grid-cols-10 gap-1" id="penampilan-buttons">
                        <!-- Buttons will be generated by JavaScript -->
                    </div>
                </div>
            </div>

            <!-- Total Score -->
            <div class="bg-white rounded-lg shadow p-6 flex flex-col justify-center text-center">
                <h2 class="text-xl font-bold text-gray-800 mb-4">TOTAL SCORE</h2>
                <div class="bg-gradient-to-br from-blue-500 to-blue-600 text-white rounded-lg p-6 mb-4">
                    <div class="text-5xl font-bold" id="total-score">9.10</div>
                    <div class="text-blue-100 mt-1">/ 10.00</div>
                </div>
                
                <!-- Action Button -->
                <button id="submit-button" onclick="submitScores()" 
                        class="bg-green-600 hover:bg-green-700 text-white font-semibold py-3 px-4 rounded-lg transition-colors">
                    Submit Penilaian
                </button>
            </div>
        </div>
    </main>

    <script>
        console.log(document.getElementById('unit_id').value);
        // =====================================================================
        // KONFIGURASI & STATE
        // =====================================================================
        let scores = {
            teknik: 0,
            kekuatan: 0,
            penampilan: 0
        };
        let isLoading = false; // Untuk anti-race condition
        const BASE_SCORE = 9.10; // Skor dasar

        // Ambil data dari HTML
        const PERTANDINGAN_ID = document.getElementById('pertandingan_id').value;
        const JURI_ID = document.getElementById('juri_id').value;
        const ROLE_JURI = document.getElementById('role_juri').value;

        // =====================================================================
        // FUNGSI PENGIRIMAN DATA (ANTI-RACE CONDITION)
        // =====================================================================
        
        function toggleAllButtons(disabled) {
            isLoading = disabled;
            const allButtons = document.querySelectorAll('button');
            allButtons.forEach(button => {
                button.disabled = disabled;
                button.classList.toggle('opacity-75', disabled);
                if (disabled) {
                    button.classList.add('cursor-wait');
                } else {
                    button.classList.remove('cursor-wait');
                }
            });
        }

        function kirimPoinSeni(type, poin) {
            if (isLoading) {
                console.log("Request sedang diproses, mohon tunggu...");
                return;
            }
            toggleAllButtons(true);

            fetch(`/kirim-poin-seni/${JURI_ID}`, {
                method: "POST",
                headers: {
                    "X-CSRF-TOKEN": document.querySelector('meta[name="csrf-token"]').getAttribute("content"),
                    "Content-Type": "application/json",
                },
                body: JSON.stringify({
                    poin: poin,
                    type: type, // 'teknik', 'kekuatan', 'penampilan'
                    filter: 'penilaian_ganda', // Filter statis untuk halaman ini
                    pertandingan_id: PERTANDINGAN_ID,
                    role: ROLE_JURI,
                    unit_id: document.getElementById('unit_id').value,
                }),
            })
            .then(res => {
                if (!res.ok) throw new Error('Network response was not ok');
                return res.json();
            })
            .then(data => {
                console.log(`Data untuk ${type} berhasil dikirim:`, data);
            })
            .catch(error => {
                console.error("Fetch error:", error);
                alert("Terjadi kesalahan saat mengirim data. Silakan coba lagi.");
            })
            .finally(() => {
                toggleAllButtons(false);
            });
        }
        
        // =====================================================================
        // FUNGSI UI
        // =====================================================================

        // Generate score buttons for each category
        function generateButtons(containerId, category) {
            const container = document.getElementById(containerId);
            container.innerHTML = '';
            
            for (let i = 1; i <= 30; i++) {
                const value = (i * 0.01).toFixed(2);
                const button = document.createElement('button');
                button.className = 'w-8 h-8 border border-gray-300 rounded text-xs font-medium hover:bg-blue-100 hover:border-blue-300 transition-colors focus:outline-none';
                button.textContent = value;
                button.onclick = () => selectScore(category, parseFloat(value), button, containerId);
                container.appendChild(button);
            }
        }

        // Select score function
        function selectScore(category, value, selectedButton, containerId) {
            // Remove active state from all buttons in this category
            const container = document.getElementById(containerId);
            const buttons = container.querySelectorAll('button');
            buttons.forEach(btn => {
                btn.className = 'w-8 h-8 border border-gray-300 rounded text-xs font-medium hover:bg-blue-100 hover:border-blue-300 transition-colors focus:outline-none';
            });

            // Add active state to selected button
            selectedButton.className = 'w-8 h-8 border-2 border-blue-600 bg-blue-600 text-white rounded text-xs font-bold transition-colors focus:outline-none';

            // Update local score
            scores[category] = value;
            document.getElementById(category + '-score').textContent = value.toFixed(2);
            
            // Update total
            updateTotal();
            
            // Kirim event ke server
            kirimPoinSeni(category, value);
        }

        // Update total score
        function updateTotal() {
            const total = BASE_SCORE + scores.teknik + scores.kekuatan + scores.penampilan;
            document.getElementById('total-score').textContent = total.toFixed(2);
        }

        // Submit (konfirmasi akhir)
        function submitScores() {
            const total = BASE_SCORE + scores.teknik + scores.kekuatan + scores.penampilan;
            alert(`Penilaian berhasil disubmit!\n\nTotal Score: ${total.toFixed(2)}`);
            // Di sini Anda bisa menambahkan logika fetch untuk konfirmasi akhir jika perlu
        }

        // Initialize buttons on page load
        document.addEventListener('DOMContentLoaded', function() {
            generateButtons('teknik-buttons', 'teknik');
            generateButtons('kekuatan-buttons', 'kekuatan');
            generateButtons('penampilan-buttons', 'penampilan');
        });
    </script>
</body>
</html>