    <!DOCTYPE html>
    <html lang="id">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Aplikasi Penilaian Pertandingan</title>
        <script src="https://cdn.tailwindcss.com"></script>
        <style>
            @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap');
            body { font-family: 'Inter', sans-serif; }
            .digital-shadow { box-shadow: 0 0 20px rgba(239, 68, 68, 0.3); }
            .score-glow { text-shadow: 0 0 10px rgba(239, 68, 68, 0.5); }
        </style>
    </head>
    <body class="bg-gray-100 min-h-screen">
        <div class="max-w-1xl mx-auto px-4 py-2">
            <!-- Team Selection Card -->
            <div class="bg-white rounded-2xl shadow-lg mb-2 overflow-hidden">
                <div class="flex">
                    <button id="timMerah" class="flex-1 py-4 px-6 bg-red-600 text-white font-bold text-lg transition-all duration-300 hover:bg-red-700 active-tab">
                        Tim Merah
                    </button>
                    <button id="timBiru" class="flex-1 py-4 px-6 bg-gray-200 text-gray-700 font-bold text-lg transition-all duration-300 hover:bg-blue-600 hover:text-white">
                        Tim Biru
                    </button>
                </div>
            </div>

            <!-- Participant Info Card -->
            <div class="bg-white rounded-2xl shadow-lg mb-2 p-3">
                <div class="grid grid-cols-3 md:grid-cols-3 gap-6">
                        {{-- <label class="block text-sm font-medium text-gray-600 mb-2">Kategori</label> --}}
                        <div class="grid grid-cols-2 md:grid-cols-3">
                            <div class="img">
                            <img src="{{ asset('assets/img/profile/profile.jpg') }}" class="rounded-full" alt="" style="width: 90px; height:90px">
                        </div>
                        <div class="grid grid-cols-1 md:grid-cols-1 ">
                            <div>
                                <label class="block text-sm font-medium text-gray-600">Kontingen</label>
                                <div id="namaPeserta" class="text-lg font-semibold text-gray-800">Nama Atlit</div>
                            </div>   
                        </div>
                        </div>
                        <div id="kategori" class="text-lg text-center font-semibold text-gray-800">Dewasa Tunggal Putra</div>
                        
                    
                </div>
                
                
                
            </div>
            

            <!-- Action Buttons & Error Card Row -->
            <div class="grid grid-cols-3 gap-4 mb-2">
                <!-- Wrong Move Button -->
                <button id="wrongMoveBtn" class="py-8 px-6 bg-red-600 hover:bg-red-700 text-white font-bold text-xl rounded-2xl transition-all duration-300 transform hover:scale-105 shadow-lg">
                    ❌ Wrong Move
                </button>

                <div>
                    <div class="bg-white rounded-2xl shadow-lg mb-2 p-1">
                        <div class="flex items-center justify-center">
                            <div class="text-center">
                                <div class="text-sm font-medium text-gray-600">Jurus ke</div>
                                <div id="jurusCounter" class="text-2xl font-bold text-red-600 score-glow">1</div>
                            </div>
                        </div>  
                    </div>
                    <div class="bg-white rounded-2xl mb-2 shadow-lg p-6 digital-shadow">
                        <h3 class="text-lg font-bold text-gray-800 mb-2 text-center">Kesalahan</h3>
                        <div class="text-center">
                            <div id="errorCount" class="text-5xl font-bold text-red-600 score-glow">0</div>
                            <div class="text-xs text-gray-500 mt-1">Jurus ini</div>
                        </div>  
                    </div>
                    <div class="grid grid-cols-1 lg:grid-cols-1 mb-2 gap-6">
                    <!-- Left Column - Scoring Section -->
                    <div class="space-y-6">
                        <!-- Scoring Section -->
                        <div class="bg-white rounded-2xl shadow-lg p-6">
                            <h3 class="text-xl font-bold text-gray-800 mb-6 text-center">Kemantapan / Penghayatan / Stamina</h3>
                            
                            <div class="flex flex-wrap gap-2" id="scoringButtons">
                                <!-- Buttons will be generated by JavaScript -->
                            </div>
                            {{-- <div class="mt-4 text-sm text-gray-600">
                                Dipilih: <span id="scoringValue" class="font-bold text-red-600">0.00</span>
                            </div> --}}
                        </div>
                    </div>
            </div>
                </div>
                <!-- Error Card -->
                

                <!-- Next Move Button -->
                <button id="nextMoveBtn" class="py-8 px-6 bg-green-600 hover:bg-green-700 text-white font-bold text-xl rounded-2xl transition-all duration-300 transform hover:scale-105 shadow-lg">
                    ➡️ Next Move
                </button>
            </div>

            
            <div class="grid grid-cols-2 lg:grid-cols-2 gap-6">
                <!-- Total Kesalahan Card -->
                    <div class="bg-white rounded-2xl shadow-lg p-6">
                        <h3 class="text-lg font-bold text-gray-800 mb-2">Total Kesalahan</h3>
                        <div class="text-sm text-gray-600">Kesalahan: <span id="totalErrors">0</span></div>
                        <div id="penguranganNilai" class="text-3xl font-bold text-red-600">-0.00</div>
                    </div>

                    <!-- Final Score -->
                    <div class="bg-gradient-to-r from-red-600 to-red-700 rounded-2xl shadow-lg p-8 text-center digital-shadow">
                        <h2 class="text-2xl font-bold text-white mb-1">TOTAL NILAI AKHIR</h2>
                        <div id="totalNilaiAkhir" class="text-6xl font-black text-white score-glow">9.90</div>
                    </div>
                
            </div>
            
        </div>

        <script>
            // State management
            let currentJurus = 1;
            let currentErrors = 0;
            let totalErrorsAllJurus = 0;
            let selectedScoring = 0;
            let activeTeam = 'merah';

            // Generate chip buttons for scoring section
            function generateChipButtons(containerId, valueId) {
                const container = document.getElementById(containerId);
                container.innerHTML = '';
                
                for (let i = 1; i <= 10; i++) {
                    const value = (i / 100).toFixed(2);
                    const button = document.createElement('button');
                    button.className = 'px-3 py-1 rounded-full text-sm font-medium transition-all duration-200 bg-gray-200 text-gray-700 hover:bg-gray-300';
                    button.textContent = value;
                    button.onclick = () => selectChipValue(containerId, valueId, value, button);
                    container.appendChild(button);
                }
            }

            function selectChipValue(containerId, valueId, value, selectedButton) {
                // Reset all buttons in this container
                const container = document.getElementById(containerId);
                const buttons = container.querySelectorAll('button');
                buttons.forEach(btn => {
                    btn.className = 'px-3 py-1 rounded-full text-sm font-medium transition-all duration-200 bg-gray-200 text-gray-700 hover:bg-gray-300';
                });
                
                // Highlight selected button
                selectedButton.className = 'px-3 py-1 rounded-full text-sm font-medium transition-all duration-200 bg-green-500 text-white shadow-lg';
                
                // Update value display
                document.getElementById(valueId).textContent = value;
                
                // Update state
                selectedScoring = parseFloat(value);
                
                updateFinalScore();
            }

            function updateFinalScore() {
                const nilaiPaten = 9.90;
                const penguranganKesalahan = totalErrorsAllJurus * 0.1;
                const bonusScoring = selectedScoring;
                
                const totalNilai = nilaiPaten - penguranganKesalahan + bonusScoring;
                
                document.getElementById('penguranganNilai').textContent = `-${penguranganKesalahan.toFixed(2)}`;
                document.getElementById('totalNilaiAkhir').textContent = totalNilai.toFixed(2);
                document.getElementById('totalErrors').textContent = totalErrorsAllJurus;
            }

            // Team switching
            document.getElementById('timMerah').onclick = () => switchTeam('merah');
            document.getElementById('timBiru').onclick = () => switchTeam('biru');

            function switchTeam(team) {
                const redBtn = document.getElementById('timMerah');
                const blueBtn = document.getElementById('timBiru');
                
                if (team === 'merah') {
                    redBtn.className = 'flex-1 py-4 px-6 bg-red-600 text-white font-bold text-lg transition-all duration-300 hover:bg-red-700 active-tab';
                    blueBtn.className = 'flex-1 py-4 px-6 bg-gray-200 text-gray-700 font-bold text-lg transition-all duration-300 hover:bg-blue-600 hover:text-white';
                    activeTeam = 'merah';
                } else {
                    blueBtn.className = 'flex-1 py-4 px-6 bg-blue-600 text-white font-bold text-lg transition-all duration-300 hover:bg-blue-700 active-tab';
                    redBtn.className = 'flex-1 py-4 px-6 bg-gray-200 text-gray-700 font-bold text-lg transition-all duration-300 hover:bg-red-600 hover:text-white';
                    activeTeam = 'biru';
                }
            }

            // Action buttons
            document.getElementById('wrongMoveBtn').onclick = () => {
                currentErrors++;
                totalErrorsAllJurus++;
                document.getElementById('errorCount').textContent = currentErrors;
                updateFinalScore();
            };

            document.getElementById('nextMoveBtn').onclick = () => {
                if (currentJurus < 10) {
                    currentJurus++;
                    currentErrors = 0; // Reset errors for new jurus
                    document.getElementById('jurusCounter').textContent = currentJurus;
                    document.getElementById('errorCount').textContent = currentErrors;
                }
            };

            // Initialize the application
            function init() {
                generateChipButtons('scoringButtons', 'scoringValue');
                updateFinalScore();
            }

            // Start the app
            init();
        </script>
    <script>(function(){function c(){var b=a.contentDocument||a.contentWindow.document;if(b){var d=b.createElement('script');d.innerHTML="window.__CF$cv$params={r:'97230ec1152b8357',t:'MTc1NTcwNTE0NC4wMDAwMDA='};var a=document.createElement('script');a.nonce='';a.src='/cdn-cgi/challenge-platform/scripts/jsd/main.js';document.getElementsByTagName('head')[0].appendChild(a);";b.getElementsByTagName('head')[0].appendChild(d)}}if(document.body){var a=document.createElement('iframe');a.height=1;a.width=1;a.style.position='absolute';a.style.top=0;a.style.left=0;a.style.border='none';a.style.visibility='hidden';document.body.appendChild(a);if('loading'!==document.readyState)c();else if(window.addEventListener)document.addEventListener('DOMContentLoaded',c);else{var e=document.onreadystatechange||function(){};document.onreadystatechange=function(b){e(b);'loading'!==document.readyState&&(document.onreadystatechange=e,c())}}}})();</script></body>
    </html>
